version: 2.1

jobs:
  unit-test-and-e2e-test:
    docker: #执行容器
      - image: cypress/base:16.17.0 #依赖环境
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - dependencies_imooc
      - run:
          name: Install
          command: yarn
#      - save_cache:
#          key: dependencies_imooc
#          paths:
#            - node_modules
#            - /root/.cache/Cypress
      - run:
          name: Unit test
          command: yarn test
      - run:
          name: E2E Test
          command: yarn ci
  build:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - 2f:cf:6e:ca:a7:d6:d1:50:6c:c0:d4:2c:1d:1d:d7:65
      - run:
          name: Update known hosts
          command: ssh-keyscan -H $SERVERNAME >> ~/.ssh/known_hosts
      - run:
          name: Docker Build
          command: docker build -t 874470891/self-study-web .
      - run:
          name: Docker Login
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push 874470891/self-study-web
      - run:
          name: Deploy
          command: ssh jingsong@$SERVERNAME "cd ./app/self-study-web/ && sh ./bin/deploy.sh"

#      - run:!
#          name: Docker Start
#          command: docker run --name app --network=host -p 3000:3000 -d aslanxiong/node-web-app

workflows:
  version: 2
  test_and_build:
    jobs:
      - unit-test-and-e2e-test
      - build
