version: 2
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:17.2 #依赖环境
    branches: #分支
      only:
        - master
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - run:
          name: Install
          command: yarn
      - run:
          name: Test
          command: yarn test
